### ISSUE TITLE
Automatically find crates from extern crate

### ISSUE THREAD

**Issue by roblabla** [DanielKeep/cargo-script#43] opened 2017-07-27 15:08 UTC
It'd be nice if cargo script would look at every `extern crate`, and automatically add a dependency to use the latest version on crates.io. This would cut on the redundancy while probably being enough for quick scripts.

**Comment by DanielKeep** [comment] 2017-07-27 15:41
This is a duplicate of #38.

**Closed by DanielKeep** 2017-07-27 15:41 UTC
